/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NinjaApi);
  }
}(this, function(expect, NinjaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NinjaApi.AssetSchema();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AssetSchema', function() {
    it('should create an instance of AssetSchema', function() {
      // uncomment below and update the code to test AssetSchema
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be.a(NinjaApi.AssetSchema);
    });

    it('should have the property authorId (base name: "authorId")', function() {
      // uncomment below and update the code to test the property authorId
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property authorName (base name: "authorName")', function() {
      // uncomment below and update the code to test the property authorName
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property createTime (base name: "createTime")', function() {
      // uncomment below and update the code to test the property createTime
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property updateTime (base name: "updateTime")', function() {
      // uncomment below and update the code to test the property updateTime
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property assetId (base name: "assetId")', function() {
      // uncomment below and update the code to test the property assetId
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property formats (base name: "formats")', function() {
      // uncomment below and update the code to test the property formats
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property displayName (base name: "displayName")', function() {
      // uncomment below and update the code to test the property displayName
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property visibility (base name: "visibility")', function() {
      // uncomment below and update the code to test the property visibility
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property isCurated (base name: "isCurated")', function() {
      // uncomment below and update the code to test the property isCurated
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property thumbnail (base name: "thumbnail")', function() {
      // uncomment below and update the code to test the property thumbnail
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property triangleCount (base name: "triangleCount")', function() {
      // uncomment below and update the code to test the property triangleCount
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property presentationParams (base name: "presentationParams")', function() {
      // uncomment below and update the code to test the property presentationParams
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property license (base name: "license")', function() {
      // uncomment below and update the code to test the property license
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

    it('should have the property licenseVersion (base name: "licenseVersion")', function() {
      // uncomment below and update the code to test the property licenseVersion
      //var instance = new NinjaApi.AssetSchema();
      //expect(instance).to.be();
    });

  });

}));
