<?php
/**
 * Category
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NinjaAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Category Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Category
{
    /**
     * Possible values of this enum
     */
    public const MISCELLANEOUS = 'MISCELLANEOUS';

    public const ANIMALS = 'ANIMALS';

    public const ARCHITECTURE = 'ARCHITECTURE';

    public const ART = 'ART';

    public const CULTURE = 'CULTURE';

    public const EVENTS = 'EVENTS';

    public const FOOD = 'FOOD';

    public const HISTORY = 'HISTORY';

    public const HOME = 'HOME';

    public const NATURE = 'NATURE';

    public const OBJECTS = 'OBJECTS';

    public const PEOPLE = 'PEOPLE';

    public const PLACES = 'PLACES';

    public const SCIENCE = 'SCIENCE';

    public const SPORTS = 'SPORTS';

    public const TECH = 'TECH';

    public const TRANSPORT = 'TRANSPORT';

    public const TRAVEL = 'TRAVEL';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MISCELLANEOUS,
            self::ANIMALS,
            self::ARCHITECTURE,
            self::ART,
            self::CULTURE,
            self::EVENTS,
            self::FOOD,
            self::HISTORY,
            self::HOME,
            self::NATURE,
            self::OBJECTS,
            self::PEOPLE,
            self::PLACES,
            self::SCIENCE,
            self::SPORTS,
            self::TECH,
            self::TRANSPORT,
            self::TRAVEL
        ];
    }
}


