<?php
/**
 * FormatFilter
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NinjaAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * FormatFilter Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FormatFilter
{
    /**
     * Possible values of this enum
     */
    public const TILT = 'TILT';

    public const BLOCKS = 'BLOCKS';

    public const GLTF = 'GLTF';

    public const GLTF1 = 'GLTF1';

    public const GLTF22 = 'GLTF2';

    public const OBJ = 'OBJ';

    public const FBX = 'FBX';

    public const TILT2 = '-TILT';

    public const BLOCKS2 = '-BLOCKS';

    public const GLTF2 = '-GLTF';

    public const GLTF12 = '-GLTF1';

    public const GLTF22 = '-GLTF2';

    public const OBJ2 = '-OBJ';

    public const FBX2 = '-FBX';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TILT,
            self::BLOCKS,
            self::GLTF,
            self::GLTF1,
            self::GLTF22,
            self::OBJ,
            self::FBX,
            self::TILT2,
            self::BLOCKS2,
            self::GLTF2,
            self::GLTF12,
            self::GLTF22,
            self::OBJ2,
            self::FBX2
        ];
    }
}


