/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Order.
* @enum {}
* @readonly
*/
export default class Order {
    
        /**
         * value: "NEWEST"
         * @const
         */
        "NEWEST" = "NEWEST";

    
        /**
         * value: "OLDEST"
         * @const
         */
        "OLDEST" = "OLDEST";

    
        /**
         * value: "BEST"
         * @const
         */
        "BEST" = "BEST";

    
        /**
         * value: "CREATE_TIME"
         * @const
         */
        "CREATE_TIME" = "CREATE_TIME";

    
        /**
         * value: "-CREATE_TIME"
         * @const
         */
        "-CREATE_TIME" = "-CREATE_TIME";

    
        /**
         * value: "UPDATE_TIME"
         * @const
         */
        "UPDATE_TIME" = "UPDATE_TIME";

    
        /**
         * value: "-UPDATE_TIME"
         * @const
         */
        "-UPDATE_TIME" = "-UPDATE_TIME";

    
        /**
         * value: "TRIANGLE_COUNT"
         * @const
         */
        "TRIANGLE_COUNT" = "TRIANGLE_COUNT";

    
        /**
         * value: "-TRIANGLE_COUNT"
         * @const
         */
        "-TRIANGLE_COUNT" = "-TRIANGLE_COUNT";

    
        /**
         * value: "LIKED_TIME"
         * @const
         */
        "LIKED_TIME" = "LIKED_TIME";

    
        /**
         * value: "-LIKED_TIME"
         * @const
         */
        "-LIKED_TIME" = "-LIKED_TIME";

    
        /**
         * value: "LIKES"
         * @const
         */
        "LIKES" = "LIKES";

    
        /**
         * value: "-LIKES"
         * @const
         */
        "-LIKES" = "-LIKES";

    
        /**
         * value: "DOWNLOADS"
         * @const
         */
        "DOWNLOADS" = "DOWNLOADS";

    
        /**
         * value: "-DOWNLOADS"
         * @const
         */
        "-DOWNLOADS" = "-DOWNLOADS";

    
        /**
         * value: "DISPLAY_NAME"
         * @const
         */
        "DISPLAY_NAME" = "DISPLAY_NAME";

    
        /**
         * value: "-DISPLAY_NAME"
         * @const
         */
        "-DISPLAY_NAME" = "-DISPLAY_NAME";

    
        /**
         * value: "AUTHOR_NAME"
         * @const
         */
        "AUTHOR_NAME" = "AUTHOR_NAME";

    
        /**
         * value: "-AUTHOR_NAME"
         * @const
         */
        "-AUTHOR_NAME" = "-AUTHOR_NAME";

    

    /**
    * Returns a <code>Order</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Order} The enum <code>Order</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

