/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NinjaApi);
  }
}(this, function(expect, NinjaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NinjaApi.UsersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersApi', function() {
    describe('icosaApiUsersDeleteAsset', function() {
      it('should call icosaApiUsersDeleteAsset successfully', function(done) {
        //uncomment below and update the code to test icosaApiUsersDeleteAsset
        //instance.icosaApiUsersDeleteAsset(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('icosaApiUsersGetMeAsset', function() {
      it('should call icosaApiUsersGetMeAsset successfully', function(done) {
        //uncomment below and update the code to test icosaApiUsersGetMeAsset
        //instance.icosaApiUsersGetMeAsset(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('icosaApiUsersGetMeAssets', function() {
      it('should call icosaApiUsersGetMeAssets successfully', function(done) {
        //uncomment below and update the code to test icosaApiUsersGetMeAssets
        //instance.icosaApiUsersGetMeAssets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('icosaApiUsersGetMeLikedassets', function() {
      it('should call icosaApiUsersGetMeLikedassets successfully', function(done) {
        //uncomment below and update the code to test icosaApiUsersGetMeLikedassets
        //instance.icosaApiUsersGetMeLikedassets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('icosaApiUsersGetUsersMe', function() {
      it('should call icosaApiUsersGetUsersMe successfully', function(done) {
        //uncomment below and update the code to test icosaApiUsersGetUsersMe
        //instance.icosaApiUsersGetUsersMe(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('icosaApiUsersUpdateUser', function() {
      it('should call icosaApiUsersUpdateUser successfully', function(done) {
        //uncomment below and update the code to test icosaApiUsersUpdateUser
        //instance.icosaApiUsersUpdateUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
