/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AssetSchema from '../model/AssetSchema';
import Category from '../model/Category';
import Complexity from '../model/Complexity';
import FormatFilter from '../model/FormatFilter';
import LicenseFilter from '../model/LicenseFilter';
import Order from '../model/Order';
import PagedAssetSchema from '../model/PagedAssetSchema';

/**
* Assets service.
* @module api/AssetsApi
* @version 1.0.0
*/
export default class AssetsApi {

    /**
    * Constructs a new AssetsApi. 
    * @alias module:api/AssetsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the icosaApiAssetsGetAsset operation.
     * @callback module:api/AssetsApi~icosaApiAssetsGetAssetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AssetSchema} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Asset
     * @param {String} asset 
     * @param {module:api/AssetsApi~icosaApiAssetsGetAssetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AssetSchema}
     */
    icosaApiAssetsGetAsset(asset, callback) {
      let postBody = null;
      // verify the required parameter 'asset' is set
      if (asset === undefined || asset === null) {
        throw new Error("Missing the required parameter 'asset' when calling icosaApiAssetsGetAsset");
      }

      let pathParams = {
        'asset': asset
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AssetSchema;
      return this.apiClient.callApi(
        '/v1/assets/{asset}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the icosaApiAssetsGetAssets operation.
     * @callback module:api/AssetsApi~icosaApiAssetsGetAssetsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PagedAssetSchema} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Assets
     * @param {Object} opts Optional parameters
     * @param {module:model/Category} [category] 
     * @param {Boolean} [curated = false)] 
     * @param {Array.<module:model/FormatFilter>} [format] Filter by format
     * @param {String} [keywords] 
     * @param {String} [name] 
     * @param {String} [description] 
     * @param {Array.<String>} [tag] 
     * @param {module:model/Order} [orderBy] 
     * @param {module:model/Complexity} [maxComplexity] 
     * @param {Number} [triangleCountMin] 
     * @param {Number} [triangleCountMax] 
     * @param {String} [zipArchiveUrl] 
     * @param {String} [authorName] 
     * @param {module:model/LicenseFilter} [license] 
     * @param {String} [pageToken] 
     * @param {String} [pageSize] 
     * @param {module:api/AssetsApi~icosaApiAssetsGetAssetsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PagedAssetSchema}
     */
    icosaApiAssetsGetAssets(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'category': opts['category'],
        'curated': opts['curated'],
        'format': this.apiClient.buildCollectionParam(opts['format'], 'multi'),
        'keywords': opts['keywords'],
        'name': opts['name'],
        'description': opts['description'],
        'tag': this.apiClient.buildCollectionParam(opts['tag'], 'multi'),
        'orderBy': opts['orderBy'],
        'maxComplexity': opts['maxComplexity'],
        'triangleCountMin': opts['triangleCountMin'],
        'triangleCountMax': opts['triangleCountMax'],
        'zipArchiveUrl': opts['zipArchiveUrl'],
        'authorName': opts['authorName'],
        'license': opts['license'],
        'pageToken': opts['pageToken'],
        'pageSize': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = PagedAssetSchema;
      return this.apiClient.callApi(
        '/v1/assets', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
