--[[
  NinjaAPI

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- asset_filters class
local asset_filters = {}
local asset_filters_mt = {
	__name = "asset_filters";
	__index = asset_filters;
}

local function cast_asset_filters(t)
	return setmetatable(t, asset_filters_mt)
end

local function new_asset_filters(category, curated, format, keywords, name, description, tag, order_by, max_complexity, triangle_count_min, triangle_count_max, zip_archive_url, author_name, license)
	return cast_asset_filters({
		["category"] = category;
		["curated"] = curated;
		["format"] = format;
		["keywords"] = keywords;
		["name"] = name;
		["description"] = description;
		["tag"] = tag;
		["orderBy"] = order_by;
		["maxComplexity"] = max_complexity;
		["triangleCountMin"] = triangle_count_min;
		["triangleCountMax"] = triangle_count_max;
		["zipArchiveUrl"] = zip_archive_url;
		["authorName"] = author_name;
		["license"] = license;
	})
end

return {
	cast = cast_asset_filters;
	new = new_asset_filters;
}
