--[[
  NinjaAPI

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- asset_resource class
local asset_resource = {}
local asset_resource_mt = {
	__name = "asset_resource";
	__index = asset_resource;
}

local function cast_asset_resource(t)
	return setmetatable(t, asset_resource_mt)
end

local function new_asset_resource(relative_path, content_type, url)
	return cast_asset_resource({
		["relativePath"] = relative_path;
		["contentType"] = content_type;
		["url"] = url;
	})
end

return {
	cast = cast_asset_resource;
	new = new_asset_resource;
}
