--[[
  NinjaAPI

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- category class
local category = {}
local category_mt = {
	__name = "category";
	__index = category;
}

local function cast_category(t)
	return setmetatable(t, category_mt)
end

local function new_category()
	return cast_category({
	})
end

return {
	cast = cast_category;
	new = new_category;
}
