--[[
  NinjaAPI

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- login_token class
local login_token = {}
local login_token_mt = {
	__name = "login_token";
	__index = login_token;
}

local function cast_login_token(t)
	return setmetatable(t, login_token_mt)
end

local function new_login_token(access_token, token_type)
	return cast_login_token({
		["access_token"] = access_token;
		["token_type"] = token_type;
	})
end

return {
	cast = cast_login_token;
	new = new_login_token;
}
