--[[
  NinjaAPI

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- paged_asset_schema class
local paged_asset_schema = {}
local paged_asset_schema_mt = {
	__name = "paged_asset_schema";
	__index = paged_asset_schema;
}

local function cast_paged_asset_schema(t)
	return setmetatable(t, paged_asset_schema_mt)
end

local function new_paged_asset_schema(assets, total_size, next_page_token)
	return cast_paged_asset_schema({
		["assets"] = assets;
		["totalSize"] = total_size;
		["nextPageToken"] = next_page_token;
	})
end

return {
	cast = cast_paged_asset_schema;
	new = new_paged_asset_schema;
}
