--[[
  NinjaAPI

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- patch_user_schema class
local patch_user_schema = {}
local patch_user_schema_mt = {
	__name = "patch_user_schema";
	__index = patch_user_schema;
}

local function cast_patch_user_schema(t)
	return setmetatable(t, patch_user_schema_mt)
end

local function new_patch_user_schema(email, displayname, description)
	return cast_patch_user_schema({
		["email"] = email;
		["displayname"] = displayname;
		["description"] = description;
	})
end

return {
	cast = cast_patch_user_schema;
	new = new_patch_user_schema;
}
