/*
 * NinjaAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAssetsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Asset
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asset"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AssetSchema</returns>
        AssetSchema IcosaApiAssetsGetAsset(string asset, int operationIndex = 0);

        /// <summary>
        /// Get Asset
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asset"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AssetSchema</returns>
        ApiResponse<AssetSchema> IcosaApiAssetsGetAssetWithHttpInfo(string asset, int operationIndex = 0);
        /// <summary>
        /// Get Assets
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="curated"> (optional, default to false)</param>
        /// <param name="format">Filter by format (optional)</param>
        /// <param name="keywords"> (optional)</param>
        /// <param name="name"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="maxComplexity"> (optional)</param>
        /// <param name="triangleCountMin"> (optional)</param>
        /// <param name="triangleCountMax"> (optional)</param>
        /// <param name="zipArchiveUrl"> (optional)</param>
        /// <param name="authorName"> (optional)</param>
        /// <param name="license"> (optional)</param>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PagedAssetSchema</returns>
        PagedAssetSchema IcosaApiAssetsGetAssets(Category? category = default(Category?), bool? curated = default(bool?), List<FormatFilter>? format = default(List<FormatFilter>?), string? keywords = default(string?), string? name = default(string?), string? description = default(string?), List<string>? tag = default(List<string>?), Order? orderBy = default(Order?), Complexity? maxComplexity = default(Complexity?), int? triangleCountMin = default(int?), int? triangleCountMax = default(int?), string? zipArchiveUrl = default(string?), string? authorName = default(string?), LicenseFilter? license = default(LicenseFilter?), string? pageToken = default(string?), string? pageSize = default(string?), int operationIndex = 0);

        /// <summary>
        /// Get Assets
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="curated"> (optional, default to false)</param>
        /// <param name="format">Filter by format (optional)</param>
        /// <param name="keywords"> (optional)</param>
        /// <param name="name"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="maxComplexity"> (optional)</param>
        /// <param name="triangleCountMin"> (optional)</param>
        /// <param name="triangleCountMax"> (optional)</param>
        /// <param name="zipArchiveUrl"> (optional)</param>
        /// <param name="authorName"> (optional)</param>
        /// <param name="license"> (optional)</param>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PagedAssetSchema</returns>
        ApiResponse<PagedAssetSchema> IcosaApiAssetsGetAssetsWithHttpInfo(Category? category = default(Category?), bool? curated = default(bool?), List<FormatFilter>? format = default(List<FormatFilter>?), string? keywords = default(string?), string? name = default(string?), string? description = default(string?), List<string>? tag = default(List<string>?), Order? orderBy = default(Order?), Complexity? maxComplexity = default(Complexity?), int? triangleCountMin = default(int?), int? triangleCountMax = default(int?), string? zipArchiveUrl = default(string?), string? authorName = default(string?), LicenseFilter? license = default(LicenseFilter?), string? pageToken = default(string?), string? pageSize = default(string?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAssetsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Asset
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asset"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AssetSchema</returns>
        System.Threading.Tasks.Task<AssetSchema> IcosaApiAssetsGetAssetAsync(string asset, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get Asset
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asset"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AssetSchema)</returns>
        System.Threading.Tasks.Task<ApiResponse<AssetSchema>> IcosaApiAssetsGetAssetWithHttpInfoAsync(string asset, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get Assets
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="curated"> (optional, default to false)</param>
        /// <param name="format">Filter by format (optional)</param>
        /// <param name="keywords"> (optional)</param>
        /// <param name="name"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="maxComplexity"> (optional)</param>
        /// <param name="triangleCountMin"> (optional)</param>
        /// <param name="triangleCountMax"> (optional)</param>
        /// <param name="zipArchiveUrl"> (optional)</param>
        /// <param name="authorName"> (optional)</param>
        /// <param name="license"> (optional)</param>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PagedAssetSchema</returns>
        System.Threading.Tasks.Task<PagedAssetSchema> IcosaApiAssetsGetAssetsAsync(Category? category = default(Category?), bool? curated = default(bool?), List<FormatFilter>? format = default(List<FormatFilter>?), string? keywords = default(string?), string? name = default(string?), string? description = default(string?), List<string>? tag = default(List<string>?), Order? orderBy = default(Order?), Complexity? maxComplexity = default(Complexity?), int? triangleCountMin = default(int?), int? triangleCountMax = default(int?), string? zipArchiveUrl = default(string?), string? authorName = default(string?), LicenseFilter? license = default(LicenseFilter?), string? pageToken = default(string?), string? pageSize = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get Assets
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="curated"> (optional, default to false)</param>
        /// <param name="format">Filter by format (optional)</param>
        /// <param name="keywords"> (optional)</param>
        /// <param name="name"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="maxComplexity"> (optional)</param>
        /// <param name="triangleCountMin"> (optional)</param>
        /// <param name="triangleCountMax"> (optional)</param>
        /// <param name="zipArchiveUrl"> (optional)</param>
        /// <param name="authorName"> (optional)</param>
        /// <param name="license"> (optional)</param>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PagedAssetSchema)</returns>
        System.Threading.Tasks.Task<ApiResponse<PagedAssetSchema>> IcosaApiAssetsGetAssetsWithHttpInfoAsync(Category? category = default(Category?), bool? curated = default(bool?), List<FormatFilter>? format = default(List<FormatFilter>?), string? keywords = default(string?), string? name = default(string?), string? description = default(string?), List<string>? tag = default(List<string>?), Order? orderBy = default(Order?), Complexity? maxComplexity = default(Complexity?), int? triangleCountMin = default(int?), int? triangleCountMax = default(int?), string? zipArchiveUrl = default(string?), string? authorName = default(string?), LicenseFilter? license = default(LicenseFilter?), string? pageToken = default(string?), string? pageSize = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAssetsApi : IAssetsApiSync, IAssetsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AssetsApi : IAssetsApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AssetsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AssetsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssetsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AssetsApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssetsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AssetsApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssetsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AssetsApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Asset 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asset"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AssetSchema</returns>
        public AssetSchema IcosaApiAssetsGetAsset(string asset, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<AssetSchema> localVarResponse = IcosaApiAssetsGetAssetWithHttpInfo(asset);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Asset 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asset"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AssetSchema</returns>
        public Org.OpenAPITools.Client.ApiResponse<AssetSchema> IcosaApiAssetsGetAssetWithHttpInfo(string asset, int operationIndex = 0)
        {
            // verify the required parameter 'asset' is set
            if (asset == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'asset' when calling AssetsApi->IcosaApiAssetsGetAsset");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("asset", Org.OpenAPITools.Client.ClientUtils.ParameterToString(asset)); // path parameter

            localVarRequestOptions.Operation = "AssetsApi.IcosaApiAssetsGetAsset";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<AssetSchema>("/v1/assets/{asset}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("IcosaApiAssetsGetAsset", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Asset 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asset"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AssetSchema</returns>
        public async System.Threading.Tasks.Task<AssetSchema> IcosaApiAssetsGetAssetAsync(string asset, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<AssetSchema> localVarResponse = await IcosaApiAssetsGetAssetWithHttpInfoAsync(asset, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Asset 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="asset"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AssetSchema)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<AssetSchema>> IcosaApiAssetsGetAssetWithHttpInfoAsync(string asset, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'asset' is set
            if (asset == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'asset' when calling AssetsApi->IcosaApiAssetsGetAsset");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("asset", Org.OpenAPITools.Client.ClientUtils.ParameterToString(asset)); // path parameter

            localVarRequestOptions.Operation = "AssetsApi.IcosaApiAssetsGetAsset";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<AssetSchema>("/v1/assets/{asset}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("IcosaApiAssetsGetAsset", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Assets 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="curated"> (optional, default to false)</param>
        /// <param name="format">Filter by format (optional)</param>
        /// <param name="keywords"> (optional)</param>
        /// <param name="name"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="maxComplexity"> (optional)</param>
        /// <param name="triangleCountMin"> (optional)</param>
        /// <param name="triangleCountMax"> (optional)</param>
        /// <param name="zipArchiveUrl"> (optional)</param>
        /// <param name="authorName"> (optional)</param>
        /// <param name="license"> (optional)</param>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PagedAssetSchema</returns>
        public PagedAssetSchema IcosaApiAssetsGetAssets(Category? category = default(Category?), bool? curated = default(bool?), List<FormatFilter>? format = default(List<FormatFilter>?), string? keywords = default(string?), string? name = default(string?), string? description = default(string?), List<string>? tag = default(List<string>?), Order? orderBy = default(Order?), Complexity? maxComplexity = default(Complexity?), int? triangleCountMin = default(int?), int? triangleCountMax = default(int?), string? zipArchiveUrl = default(string?), string? authorName = default(string?), LicenseFilter? license = default(LicenseFilter?), string? pageToken = default(string?), string? pageSize = default(string?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<PagedAssetSchema> localVarResponse = IcosaApiAssetsGetAssetsWithHttpInfo(category, curated, format, keywords, name, description, tag, orderBy, maxComplexity, triangleCountMin, triangleCountMax, zipArchiveUrl, authorName, license, pageToken, pageSize);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Assets 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="curated"> (optional, default to false)</param>
        /// <param name="format">Filter by format (optional)</param>
        /// <param name="keywords"> (optional)</param>
        /// <param name="name"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="maxComplexity"> (optional)</param>
        /// <param name="triangleCountMin"> (optional)</param>
        /// <param name="triangleCountMax"> (optional)</param>
        /// <param name="zipArchiveUrl"> (optional)</param>
        /// <param name="authorName"> (optional)</param>
        /// <param name="license"> (optional)</param>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PagedAssetSchema</returns>
        public Org.OpenAPITools.Client.ApiResponse<PagedAssetSchema> IcosaApiAssetsGetAssetsWithHttpInfo(Category? category = default(Category?), bool? curated = default(bool?), List<FormatFilter>? format = default(List<FormatFilter>?), string? keywords = default(string?), string? name = default(string?), string? description = default(string?), List<string>? tag = default(List<string>?), Order? orderBy = default(Order?), Complexity? maxComplexity = default(Complexity?), int? triangleCountMin = default(int?), int? triangleCountMax = default(int?), string? zipArchiveUrl = default(string?), string? authorName = default(string?), LicenseFilter? license = default(LicenseFilter?), string? pageToken = default(string?), string? pageSize = default(string?), int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (category != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "category", category));
            }
            if (curated != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "curated", curated));
            }
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("multi", "format", format));
            }
            if (keywords != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "keywords", keywords));
            }
            if (name != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "name", name));
            }
            if (description != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "description", description));
            }
            if (tag != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("multi", "tag", tag));
            }
            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "orderBy", orderBy));
            }
            if (maxComplexity != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "maxComplexity", maxComplexity));
            }
            if (triangleCountMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "triangleCountMin", triangleCountMin));
            }
            if (triangleCountMax != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "triangleCountMax", triangleCountMax));
            }
            if (zipArchiveUrl != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "zipArchiveUrl", zipArchiveUrl));
            }
            if (authorName != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "authorName", authorName));
            }
            if (license != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "license", license));
            }
            if (pageToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "pageToken", pageToken));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }

            localVarRequestOptions.Operation = "AssetsApi.IcosaApiAssetsGetAssets";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<PagedAssetSchema>("/v1/assets", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("IcosaApiAssetsGetAssets", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Assets 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="curated"> (optional, default to false)</param>
        /// <param name="format">Filter by format (optional)</param>
        /// <param name="keywords"> (optional)</param>
        /// <param name="name"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="maxComplexity"> (optional)</param>
        /// <param name="triangleCountMin"> (optional)</param>
        /// <param name="triangleCountMax"> (optional)</param>
        /// <param name="zipArchiveUrl"> (optional)</param>
        /// <param name="authorName"> (optional)</param>
        /// <param name="license"> (optional)</param>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PagedAssetSchema</returns>
        public async System.Threading.Tasks.Task<PagedAssetSchema> IcosaApiAssetsGetAssetsAsync(Category? category = default(Category?), bool? curated = default(bool?), List<FormatFilter>? format = default(List<FormatFilter>?), string? keywords = default(string?), string? name = default(string?), string? description = default(string?), List<string>? tag = default(List<string>?), Order? orderBy = default(Order?), Complexity? maxComplexity = default(Complexity?), int? triangleCountMin = default(int?), int? triangleCountMax = default(int?), string? zipArchiveUrl = default(string?), string? authorName = default(string?), LicenseFilter? license = default(LicenseFilter?), string? pageToken = default(string?), string? pageSize = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<PagedAssetSchema> localVarResponse = await IcosaApiAssetsGetAssetsWithHttpInfoAsync(category, curated, format, keywords, name, description, tag, orderBy, maxComplexity, triangleCountMin, triangleCountMax, zipArchiveUrl, authorName, license, pageToken, pageSize, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Assets 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="category"> (optional)</param>
        /// <param name="curated"> (optional, default to false)</param>
        /// <param name="format">Filter by format (optional)</param>
        /// <param name="keywords"> (optional)</param>
        /// <param name="name"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="tag"> (optional)</param>
        /// <param name="orderBy"> (optional)</param>
        /// <param name="maxComplexity"> (optional)</param>
        /// <param name="triangleCountMin"> (optional)</param>
        /// <param name="triangleCountMax"> (optional)</param>
        /// <param name="zipArchiveUrl"> (optional)</param>
        /// <param name="authorName"> (optional)</param>
        /// <param name="license"> (optional)</param>
        /// <param name="pageToken"> (optional)</param>
        /// <param name="pageSize"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PagedAssetSchema)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<PagedAssetSchema>> IcosaApiAssetsGetAssetsWithHttpInfoAsync(Category? category = default(Category?), bool? curated = default(bool?), List<FormatFilter>? format = default(List<FormatFilter>?), string? keywords = default(string?), string? name = default(string?), string? description = default(string?), List<string>? tag = default(List<string>?), Order? orderBy = default(Order?), Complexity? maxComplexity = default(Complexity?), int? triangleCountMin = default(int?), int? triangleCountMax = default(int?), string? zipArchiveUrl = default(string?), string? authorName = default(string?), LicenseFilter? license = default(LicenseFilter?), string? pageToken = default(string?), string? pageSize = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (category != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "category", category));
            }
            if (curated != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "curated", curated));
            }
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("multi", "format", format));
            }
            if (keywords != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "keywords", keywords));
            }
            if (name != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "name", name));
            }
            if (description != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "description", description));
            }
            if (tag != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("multi", "tag", tag));
            }
            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "orderBy", orderBy));
            }
            if (maxComplexity != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "maxComplexity", maxComplexity));
            }
            if (triangleCountMin != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "triangleCountMin", triangleCountMin));
            }
            if (triangleCountMax != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "triangleCountMax", triangleCountMax));
            }
            if (zipArchiveUrl != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "zipArchiveUrl", zipArchiveUrl));
            }
            if (authorName != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "authorName", authorName));
            }
            if (license != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "license", license));
            }
            if (pageToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "pageToken", pageToken));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }

            localVarRequestOptions.Operation = "AssetsApi.IcosaApiAssetsGetAssets";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<PagedAssetSchema>("/v1/assets", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("IcosaApiAssetsGetAssets", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
