/*
 * NinjaAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Complexity {
    #[serde(rename = "COMPLEX")]
    Complex,
    #[serde(rename = "MEDIUM")]
    Medium,
    #[serde(rename = "SIMPLE")]
    Simple,

}

impl std::fmt::Display for Complexity {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Complex => write!(f, "COMPLEX"),
            Self::Medium => write!(f, "MEDIUM"),
            Self::Simple => write!(f, "SIMPLE"),
        }
    }
}

impl Default for Complexity {
    fn default() -> Complexity {
        Self::Complex
    }
}

