/*
 * NinjaAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PagedAssetSchema {
    #[serde(rename = "assets")]
    pub assets: Vec<models::AssetSchema>,
    #[serde(rename = "totalSize")]
    pub total_size: i32,
    #[serde(rename = "nextPageToken", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<Option<String>>,
}

impl PagedAssetSchema {
    pub fn new(assets: Vec<models::AssetSchema>, total_size: i32) -> PagedAssetSchema {
        PagedAssetSchema {
            assets,
            total_size,
            next_page_token: None,
        }
    }
}

