--[[
  NinjaAPI

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.api.login_api
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("login_api", function()
  local openapiclient_login_api = require "openapiclient.api.login_api"
  -- unit tests for icosa_api_login_device_login
  describe("icosa_api_login_device_login test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
