--[[
  NinjaAPI

  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.api.users_api
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("users_api", function()
  local openapiclient_users_api = require "openapiclient.api.users_api"
  -- unit tests for icosa_api_users_delete_asset
  describe("icosa_api_users_delete_asset test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for icosa_api_users_get_me_asset
  describe("icosa_api_users_get_me_asset test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for icosa_api_users_get_me_assets
  describe("icosa_api_users_get_me_assets test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for icosa_api_users_get_me_likedassets
  describe("icosa_api_users_get_me_likedassets test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for icosa_api_users_get_users_me
  describe("icosa_api_users_get_users_me test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for icosa_api_users_update_user
  describe("icosa_api_users_update_user test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
