/*
 * NinjaAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AssetResource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetResourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetResource
        //private AssetResource instance;

        public AssetResourceTests()
        {
            // TODO uncomment below to create an instance of AssetResource
            //instance = new AssetResource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetResource
        /// </summary>
        [Fact]
        public void AssetResourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssetResource
            //Assert.IsType<AssetResource>(instance);
        }

        /// <summary>
        /// Test the property 'RelativePath'
        /// </summary>
        [Fact]
        public void RelativePathTest()
        {
            // TODO unit test for the property 'RelativePath'
        }

        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Fact]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
