/*
 * NinjaAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AssetSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetSchema
        //private AssetSchema instance;

        public AssetSchemaTests()
        {
            // TODO uncomment below to create an instance of AssetSchema
            //instance = new AssetSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetSchema
        /// </summary>
        [Fact]
        public void AssetSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssetSchema
            //Assert.IsType<AssetSchema>(instance);
        }

        /// <summary>
        /// Test the property 'AuthorId'
        /// </summary>
        [Fact]
        public void AuthorIdTest()
        {
            // TODO unit test for the property 'AuthorId'
        }

        /// <summary>
        /// Test the property 'AuthorName'
        /// </summary>
        [Fact]
        public void AuthorNameTest()
        {
            // TODO unit test for the property 'AuthorName'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Fact]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }

        /// <summary>
        /// Test the property 'UpdateTime'
        /// </summary>
        [Fact]
        public void UpdateTimeTest()
        {
            // TODO unit test for the property 'UpdateTime'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'AssetId'
        /// </summary>
        [Fact]
        public void AssetIdTest()
        {
            // TODO unit test for the property 'AssetId'
        }

        /// <summary>
        /// Test the property 'Formats'
        /// </summary>
        [Fact]
        public void FormatsTest()
        {
            // TODO unit test for the property 'Formats'
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }

        /// <summary>
        /// Test the property 'Visibility'
        /// </summary>
        [Fact]
        public void VisibilityTest()
        {
            // TODO unit test for the property 'Visibility'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'IsCurated'
        /// </summary>
        [Fact]
        public void IsCuratedTest()
        {
            // TODO unit test for the property 'IsCurated'
        }

        /// <summary>
        /// Test the property 'Thumbnail'
        /// </summary>
        [Fact]
        public void ThumbnailTest()
        {
            // TODO unit test for the property 'Thumbnail'
        }

        /// <summary>
        /// Test the property 'TriangleCount'
        /// </summary>
        [Fact]
        public void TriangleCountTest()
        {
            // TODO unit test for the property 'TriangleCount'
        }

        /// <summary>
        /// Test the property 'PresentationParams'
        /// </summary>
        [Fact]
        public void PresentationParamsTest()
        {
            // TODO unit test for the property 'PresentationParams'
        }

        /// <summary>
        /// Test the property 'License'
        /// </summary>
        [Fact]
        public void LicenseTest()
        {
            // TODO unit test for the property 'License'
        }

        /// <summary>
        /// Test the property 'LicenseVersion'
        /// </summary>
        [Fact]
        public void LicenseVersionTest()
        {
            // TODO unit test for the property 'LicenseVersion'
        }
    }
}
