/*
 * NinjaAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AssetFilters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssetFiltersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssetFilters
        //private AssetFilters instance;

        public AssetFiltersTests()
        {
            // TODO uncomment below to create an instance of AssetFilters
            //instance = new AssetFilters();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetFilters
        /// </summary>
        [Test]
        public void AssetFiltersInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssetFilters
            //Assert.IsType<AssetFilters>(instance);
        }

        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Curated'
        /// </summary>
        [Test]
        public void CuratedTest()
        {
            // TODO unit test for the property 'Curated'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'Keywords'
        /// </summary>
        [Test]
        public void KeywordsTest()
        {
            // TODO unit test for the property 'Keywords'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Test]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'OrderBy'
        /// </summary>
        [Test]
        public void OrderByTest()
        {
            // TODO unit test for the property 'OrderBy'
        }
        /// <summary>
        /// Test the property 'MaxComplexity'
        /// </summary>
        [Test]
        public void MaxComplexityTest()
        {
            // TODO unit test for the property 'MaxComplexity'
        }
        /// <summary>
        /// Test the property 'TriangleCountMin'
        /// </summary>
        [Test]
        public void TriangleCountMinTest()
        {
            // TODO unit test for the property 'TriangleCountMin'
        }
        /// <summary>
        /// Test the property 'TriangleCountMax'
        /// </summary>
        [Test]
        public void TriangleCountMaxTest()
        {
            // TODO unit test for the property 'TriangleCountMax'
        }
        /// <summary>
        /// Test the property 'ZipArchiveUrl'
        /// </summary>
        [Test]
        public void ZipArchiveUrlTest()
        {
            // TODO unit test for the property 'ZipArchiveUrl'
        }
        /// <summary>
        /// Test the property 'AuthorName'
        /// </summary>
        [Test]
        public void AuthorNameTest()
        {
            // TODO unit test for the property 'AuthorName'
        }
        /// <summary>
        /// Test the property 'License'
        /// </summary>
        [Test]
        public void LicenseTest()
        {
            // TODO unit test for the property 'License'
        }
    }
}
