/*
 * NinjaAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing FormatFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FormatFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FormatFilter
        //private FormatFilter instance;

        public FormatFilterTests()
        {
            // TODO uncomment below to create an instance of FormatFilter
            //instance = new FormatFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FormatFilter
        /// </summary>
        [Test]
        public void FormatFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" FormatFilter
            //Assert.IsType<FormatFilter>(instance);
        }

    }
}
