/*
 * NinjaAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Input
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Input
        //private Input instance;

        public InputTests()
        {
            // TODO uncomment below to create an instance of Input
            //instance = new Input();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Input
        /// </summary>
        [Test]
        public void InputInstanceTest()
        {
            // TODO uncomment below to test "IsType" Input
            //Assert.IsType<Input>(instance);
        }

        /// <summary>
        /// Test the property 'PageToken'
        /// </summary>
        [Test]
        public void PageTokenTest()
        {
            // TODO unit test for the property 'PageToken'
        }
        /// <summary>
        /// Test the property 'PageToken'
        /// </summary>
        [Test]
        public void PageTokenTest()
        {
            // TODO unit test for the property 'PageToken'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Test]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Test]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
    }
}
