/*
 * NinjaAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;
using NUnit.Framework;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PatchUserSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PatchUserSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PatchUserSchema
        //private PatchUserSchema instance;

        public PatchUserSchemaTests()
        {
            // TODO uncomment below to create an instance of PatchUserSchema
            //instance = new PatchUserSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PatchUserSchema
        /// </summary>
        [Test]
        public void PatchUserSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsType" PatchUserSchema
            //Assert.IsType<PatchUserSchema>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Displayname'
        /// </summary>
        [Test]
        public void DisplaynameTest()
        {
            // TODO unit test for the property 'Displayname'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
    }
}
